### ISSUE TITLE
Update action to Node@16

### ISSUE THREAD

**Issue by waldekmastykarz** [al-cheb/configure-pagefile-action#14]
Hey @al-cheb, were you planning to update the action to Node@16? Seems like Node@12 is deprecated and all actions should be updated to 16. Happy to submit a PR if that helps.

**Comment by lazka** [comment]
#6 would also solve this I guess :)

**Comment by waldekmastykarz** [comment]
#6 is a larger change that contains other adjustments and requires more time to review. Let's hear from @al-cheb how he'd prefer to go about it 🙂

**Comment by al-cheb** [comment]
@waldekmastykarz , thank you for bringing to my attention it. I have released a new v1.3 version.
